CREATE TABLE tabungan (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id TEXT NOT NULL,
  bulan TEXT NOT NULL,
  mas INTEGER DEFAULT 0,
  adek INTEGER DEFAULT 0,
  total INTEGER DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE targets (
  user_id TEXT PRIMARY KEY,
  target_amount INTEGER NOT NULL
);
